language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
services:
  - redis-server
install:
  - sudo apt-get install redis-server
  - pip install redis
before_script:
  - sudo restart redis-server
  - redis-cli info
script:
  - nosetests
